### PR TITLE
Add monthly downloads badge to README

### PR DESCRIPTION
**Pull request by Aman-Clement**
Added a monthly downloads badge by pip Trends to the README which updated daily.
View more at - https://piptrends.com/widgets/pyserde

### CODE REVIEW

**Review by yukinarit — APPROVED** [review]
Thanks!

**Comment by ixmatus** [comment]
@yukinarit IMHO you should revert this change.

This person tried to open this exact PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). This is a promotional campaign and they (or colleagues) appear to be doing it on reddit too, I think this is suspicious activity. They are creating an external dependency on a web property that (as far as I can tell) is not officially blessed by pypi. I recommend rejecting this PR.

Users can get package statistics from `libraries.io` which is linked to directly by pypi itself.

**Comment by yukinarit** [comment]
Thanks @ixmatus 

@Aman-Clement  Any objections? otherwise I am reverting this change.

**Comment by ixmatus** [comment]
@yukinarit I appreciate you're giving this person the benefit of the doubt and an opportunity to object but I thought you should know that I just went through quite a few python repository PRs where this person and their colleague shot gunned this exact change.

It's either an attempt at promotion and SEO link juicing (the more innocent interpretation), or a more nefarious attempt at establishing first-time contributor trust (because they will now have "Contributor" label by their name on your repository for any PRs they open) so they can make malicious changes later.

**Comment by ayushjain01** [comment]
Thank you for your feedback and concerns. I'd like to clarify that this is not a promotional campaign. As stated in the PR description, our intention is simply to share a tool we have developed, which we believe could be beneficial to the community.

Our badge system offers highly accurate statistics, which is why we wanted to make it available. If the link to the pip trends page is a concern, we are more than willing to remove it.

We respect your decision if you prefer not to add more badges to your README. Our primary goal is to address any misunderstandings and assure you that this is a genuine effort to contribute to the open-source community by sharing our work on GitHub.

Thank you for considering our contribution.

**Pull request merged**
