### PR TITLE
add some examples 

### LINKED ISSUE #361: Add UUID example
Like https://github.com/yukinarit/pyserde/blob/main/examples/type_decimal.py

### PR DESCRIPTION
**Pull request by JWSong**
Added examples for the types below:
- UUID
- pathlib
- numpy
- ipaddress

resolves #361 , #363 , #360 , #362

### CODE REVIEW

**Comment by JWSong** [comment]
This PR and the test failure don't seem to be related. Can you check? @yukinarit

**Review by yukinarit — CHANGES_REQUESTED** [review]
Hi @JWSong!

Thank you! Please update [runner.py](https://github.com/yukinarit/pyserde/blob/main/examples/runner.py) to make sure examples are tested in CI.

**Comment by JWSong** [comment]
> Hi @JWSong!
> 
> Thank you! Please update [runner.py](https://github.com/yukinarit/pyserde/blob/main/examples/runner.py) to make sure examples are tested in CI.

Done in af77ede3f38fa9ec77bbf1320cc82161bc11d643! 

The latest version of `beartype` has a bug breaking the tests, so I have updated its version.

**Review by yukinarit — APPROVED** [review]
Thank you!

**Pull request merged**
