### PR TITLE
initial working jaxtyping serializing/deserializing

### PR DESCRIPTION
**Pull request by pablovela5620**
Jaxtyping serialization/deserializing working along with type checking with beartype #572 . This allows one to use [jaxtyping](https://github.com/patrick-kidger/jaxtyping) when serializing/deserializing and check both the dtype and the shape. Let me know if this direction makes sense!

### CODE REVIEW

**Comment by pablovela5620** [comment]
Hi @yukinarit,

I've implemented initial support for jaxtyping serialization/deserialization and all tests are passing. Before I proceed with adding specific tests for jaxtyping, could you please review the current implementation and let me know if you're happy with the direction? Any feedback would be greatly appreciated!

**Comment by pablovela5620** [comment]
Made jaxtyping an optional dep and addressed your typ comment!

**Comment by pablovela5620** [comment]
Added tests in! Let me know if there's anything else you'd like me to add/fix @yukinarit @kmsquire, otherwise I also think this is probably good to merge

**Review by yukinarit — APPROVED** [review]
Nice work! LGTM!

**Comment by yukinarit** [comment]
@pablovela5620 Is there anything you want to add before publishing v0.20.0?

**Comment by pablovela5620** [comment]
Nope, this looks good! Thanks

**Pull request merged**
