### PR TITLE
Add support for pathlib.Path fields

### PR DESCRIPTION
**Pull request by jfuechsl**
I was missing this functionality so I added it.

Signed-off-by: Johann Fuechsl <johann@fuechsl.co>

### CODE REVIEW

**Comment by yukinarit** [comment]
@jfuechsl 
Awesome! Thank you! :smiley:

**Comment by jfuechsl** [comment]
@yukinarit thank you for merging! Will you release a new version to PyPI?

**Comment by yukinarit** [comment]
@jfuechsl 
Yes, just published 0.1.2!

**Comment by jfuechsl** [comment]
Thank you very much!

**Pull request merged**
