### PR TITLE
Support Literal[...] type annotation

### LINKED ISSUE #220: Support typing.Literal as a type
The following leads to an error, but it should(?) be possible to check this:

```python
from typing import Literal
from serde import serde
from serde.json import from_json, to_json

@serde
class Foo:
    x: Literal["a","b"]
```

Running this currently gives:
```python
$ python literal_test.py
Traceback (most recent call last):
  File "/Users/kevin.squire/tmp/pyserde/literal_test.py", line 6, in <module>
    class Foo:
  File "/Users/kevin.squire/tmp/pyserde/serde/__init__.py", line 62, in serde
    return wrap(_cls)
  File "/Users/kevin.squire/tmp/pyserde/serde/__init__.py", line 55, in wrap
    serialize(cls, **kwargs)
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 245, in serialize
    return wrap(_cls)
  File "/Users/kevin.squire/tmp/pyserde/serde/se.py", line 220, in wrap
    g[typename(typ)] = typ
  File "/Users/kevin.squire/tmp/pyserde/serde/compat.py", line 138, in typename
    return typ.__name__
  File "/Users/kevin.squire/.pyenv/versions/3.9.11/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 711, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__
```

### PR DESCRIPTION
**Pull request by kmsquire**
This PR adds support for `Literal` type annotations.  It's pretty close to ready.

Fixes #220

### CODE REVIEW

**Comment by kmsquire** [comment]
@yukinarit This is ready to review.

**Comment by yukinarit** [comment]
@kmsquire

LGTM!

But, 
* Resolve the conflicts
* Could you add a simple example in `examples/`?

**Review by yukinarit — APPROVED** [review]
LGTM!

**Comment by yukinarit** [comment]
@kmsquire I am planning to push v0.7.3 soon. Is there any more feature/fix you want to include? 🤔

**Comment by kmsquire** [comment]
Thanks for asking!  I'll work on the orjson merge request when I get the chance, but it doesn't have to go in to v0.7.3.

**Pull request merged**
