### PR TITLE
Allow serializing and deserializing root dataclasses

### PR DESCRIPTION
**Pull request by Kobzol**
Final part of improving support for (de)serializing dataclasses not marked with `@serde`.

### CODE REVIEW

**Review by yukinarit — COMMENTED** [review]
LGTM, but please format the code using black, thank you!

**Comment by Kobzol** [comment]
Done.

**Review by yukinarit — APPROVED** [review]
LGTM!

**Comment by yukinarit** [comment]
@Kobzol Is there anything else you want to add before shipping new version?

**Pull request merged**
